tap "oven-sh/bun"

brew "bat"
brew "btop"
brew "cmake"
brew "cowsay"
brew "curl"
brew "deno"
brew "ffmpeg"
brew "gcc"
brew "gh"
brew "git"
brew "gnu-sed"
brew "go"
brew "golangci-lint"
brew "gpg"
brew "grep"
brew "helm"
brew "jq"
brew "kubernetes-cli"
brew "make"
brew "neofetch"
brew "unzip"
brew "wget"
brew "nginx"
brew "nmap"
brew "oven-sh/bun/bun"
brew "pipx"
brew "protobuf"
brew "pup"
# brew "pyenv-virtualenv"
brew "pyenv"
brew "thefuck"
brew "tldr"
brew "tree"
# brew "virtualenv", link: false
brew "volta"
brew "watch"
brew "yt-dlp"
brew "zsh"

cask "fig"
cask "orbstack"
cask "raycast"
cask "visual-studio-code"
# @todo more casks once stable
# @todo vscode extensions
